#!/bin/sh

# remove fluid fields from solid regions (important for post-processing)
for i in fuel cladding
do
   rm -f 0*/$i/{mut,alphat,epsilon,k,U,p_rgh}
done

for i in coolant cladding fuel
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done

